### ISSUE TITLE
cargo build fails

### ISSUE THREAD

**Issue by tonypolik** [librematch/delta-play-replay#2]
Hi, this is the output when i run `cargo build`.
[build.txt](https://github.com/user-attachments/files/16596313/build.txt)

I'm using Ubuntu 22.04.3 LTS on WSL2.
rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
cargo: 1.80.1 (376290515 2024-07-16)

When i try to build on windows, without WSL2, i get the same errors.

Am i doing something wrong?
Thanks

**Comment by oliverfenwick90** [comment]
I fixed this in #3 . Needed to update tonic and prost crates and minor adjustment to usage.

**Comment by tonypolik** [comment]
> I fixed this in #3 . Needed to update tonic and prost crates and minor adjustment to usage.

Thanks, I confirm it works. I close the issue
